[package]
name = "joybus-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
joybus-rs-core = {workspace=true}
joybus-rs-atmega328p = {workspace = true, optional=true, features=["joybus"]}

[dev-dependencies]
panic-halt.workspace = true
ufmt.workspace = true
embedded-hal.workspace = true
arduino-hal.workspace = true
joybus-rs-atmega328p.workspace = true
joybus-rs-core.workspace = true

[features]
atmega328p=["dep:joybus-rs-atmega328p"]

[workspace]
members = [
    "crates/*",
]

[workspace.dependencies]
panic-halt = "1.0.0"
ufmt = "0.2.0"
embedded-hal = "1.0"
arduino-hal = { git = "https://github.com/Rahix/avr-hal.git", rev="e5c8f37fe48419956e722490a82b9ca9b9fc61a2", features = ["arduino-nano"]}
joybus-rs-atmega328p = {path="crates/joybus-rs-atmega328p"}
joybus-rs-core = {path="crates/joybus-rs-core"}

[profile.dev]
panic = "abort"
codegen-units = 1
debug = true
lto = false  # setting this to anything higher screws up signal logic
opt-level = "s"

[profile.release]
panic = "abort"
codegen-units = 1
lto = false  # setting this to anything higher screws up signal logic
opt-level = "s"

[[example]]
name = "ocarina"
path = "examples/ocarina/main.rs"
