[general]
# if auto-detection is not working, you can hard-code a specific port here
# (the port can also be passed via the RAVEDUDE_PORT environment variable or via -P)
# port=

board = "nano"

# ravedude should open a serial console after flashing
open-console = true

# console output mode. Can be ascii, hex, dec or bin
output-mode = "ascii"

# baudrate for the serial console (this is **not** the avrdude flashing baudrate)
serial-baudrate = 57600

# time to wait for the board to be reset (in milliseconds).  this skips the manual prompt for resetting the board.
reset-delay = 2000
