[package]
name = "joybus-rs-atmega328p"
version = "0.1.0"
edition = "2021"

[dependencies]
ufmt = {workspace = true, optional=true}
joybus-rs = {workspace = true, optional=true}
arduino-hal = {workspace = true, optional=true}

[features]
default=["joybus"]
joybus=["dep:joybus-rs","dep:arduino-hal"]
ufmt=["dep:ufmt"]

[lib]
test = false
